export const authorsData = [{
      id: "1",
      name: "Jane Smith",
      email: "jane@example.com",
      bio: "Senior tech writer with 10+ years of experience in software development and technology journalism.",
      postCount: 156,
      specialty: "Technology",
      social: {
        twitter: "@janesmith",
        linkedin: "janesmith",
        github: "janesmith",
      },
      joinedDate: "2023-01-15",
      status: "active",
    },
    {
      id: "2",
      name: "John Doe",
      email: "john@example.com",
      bio: "Creative designer and UX enthusiast. Passionate about creating beautiful and functional digital experiences.",
      postCount: 98,
      specialty: "Design",
      social: {
        twitter: "@johndoe",
        linkedin: "johndoe",
      },
      joinedDate: "2023-03-20",
      status: "active",
    },
    {
      id: "3",
      name: "Sarah Wilson",
      email: "sarah@example.com",
      bio: "Business consultant and entrepreneurship advocate. Helping startups grow and scale.",
      postCount: 67,
      specialty: "Business",
      social: {
        linkedin: "sarahwilson",
      },
      joinedDate: "2023-06-10",
      status: "active",
    },
    {
      id: "4",
      name: "Mike Johnson",
      email: "mike@example.com",
      bio: "Digital marketing expert specializing in SEO and content strategy.",
      postCount: 43,
      specialty: "Marketing",
      social: {
        twitter: "@mikejohnson",
        linkedin: "mikejohnson",
      },
      joinedDate: "2023-08-05",
      status: "inactive",
    }] 
