export const mockBlogs = [
  {
    id: "post-1",
    title: "The Rise of AI",
    excerpt: "Discover how AI is changing our world...",
    category: "Tech",
    featuredImage: "/assets/blogs/ai.jpg",
    author: "Amal Nasr",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Amal",
    date: "2025-12-30",
    content:
      "Artificial Intelligence (AI) is transforming industries, automating tasks, and reshaping the future of work. Learn how AI impacts businesses and everyday life.",
    tags: ["AI", "Technology", "Innovation"],
    expertInsight:
      "Focus on AI ethics and responsible AI deployment for long-term success.",
    readTime: "9 min read",
    slug: "the-rise-of-ai",
    metaTitle: "The Rise of AI",
    status: "published",
    views: 120,
    postStatus: "pending",
    email: "amal@example.com",
  },
  {
    id: "post-2",
    title: "Healthy Living Tips",
    excerpt: "Simple tips for a healthier lifestyle...",
    category: "Lifestyle",
    featuredImage: "/assets/blogs/healthy-living.jpg",
    author: "Sara Ahmed",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sara",
    date: "2025-12-29",
    content:
      "Healthy living is about balanced nutrition, regular exercise, and mental wellness. Implement small daily habits to improve overall health.",
    tags: ["Health", "Lifestyle", "Wellness"],
    expertInsight: "Consistency is key—small changes lead to lasting results.",
    readTime: "8 min read",
    slug: "healthy-living-tips",
    metaTitle: "Healthy Living Tips",
    status: "draft",
    views: 85,
    postStatus: "approved",
    email: "sara@example.com",
    reviewedBy: "admin@example.com",
  },
  {
    id: "post-3",
    title: "Business Strategies 2025",
    excerpt: "Key strategies to grow your business...",
    category: "Business",
    featuredImage: "/assets/blogs/business.jpg",
    author: "Mohamed Ali",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Mohamed",
    date: "2025-12-28",
    content:
      "Businesses in 2025 must focus on digital transformation, customer-centric approaches, and agile methodologies to remain competitive.",
    tags: ["Business", "Strategy", "Growth"],
    expertInsight:
      "Invest in technology and employee training for sustainable growth.",
    readTime: "3 min read",
    slug: "business-strategies-2025",
    metaTitle: "Business Strategies 2025",
    status: "published",
    views: 200,
    postStatus: "published",
    email: "mohamed@example.com",
    reviewedBy: "admin@example.com",
  },
  {
    id: "post-4",
    title: "Next.js Tips",
    excerpt: "Improve your Next.js apps with these tips...",
    category: "Tech",
    featuredImage: "/assets/blogs/nextjs.jpg",
    author: "Laila Hassan",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Laila",
    date: "2025-12-27",
    content:
      "Next.js is a powerful React framework. Optimize performance, routing, and server-side rendering with these best practices.",
    tags: ["Next.js", "React", "WebDev"],
    expertInsight:
      "Use incremental static regeneration to boost performance for dynamic pages.",
    readTime: "7 min read",
    slug: "next-js-tips",
    metaTitle: "Next.js Tips",
    status: "draft",
    views: 95,
    postStatus: "rejected",
    email: "laila@example.com",
    reviewedBy: "admin@example.com",
    reviewNote: "Content needs more depth and original research",
  },
  {
    id: "post-5",
    title: "Travel on a Budget",
    excerpt: "Explore the world without breaking the bank...",
    category: "Lifestyle",
    featuredImage: "/assets/blogs/travel.jpg",
    author: "Omar Khaled",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Omar",
    date: "2025-12-26",
    content: "Budget travel is possible with careful planning...",
    tags: ["Travel", "Budget", "Tips"],
    expertInsight: "Book in advance and travel off-season for better deals.",
    readTime: "5 min read",
    slug: "travel-on-a-budget",
    metaTitle: "Travel on a Budget",
    status: "published",
    views: 140,
    postStatus: "approved",
    email: "omar@example.com",
    reviewedBy: "reviewer1@example.com",
  },
  {
    id: "post-6",
    title: "Marketing 101",
    excerpt: "Basic marketing principles you must know...",
    category: "Business",
    featuredImage: "/assets/blogs/marketing.jpg",
    author: "Hana Youssef",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Hana",
    date: "2025-12-25",
    content: "Marketing is about understanding your audience...",
    tags: ["Marketing", "Business", "Strategy"],
    expertInsight: "Focus on content and social media marketing.",
    readTime: "10 min read",
    slug: "marketing-101",
    metaTitle: "Marketing 101",
    status: "draft",
    views: 70,
    postStatus: "pending",
    email: "hana@example.com",
  },
  {
    id: "post-7",
    title: "React vs Vue",
    excerpt: "Comparing two popular frameworks...",
    category: "Tech",
    featuredImage: "/assets/blogs/react-vs-vue.jpg",
    author: "Khaled Mahmoud",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Khaled",
    date: "2025-12-24",
    content: "React and Vue are leading JavaScript frameworks...",
    tags: ["React", "Vue", "WebDev"],
    expertInsight: "Choose the framework that fits your project best.",
    readTime: "4 min read",
    slug: "react-vs-vue",
    metaTitle: "React vs Vue",
    status: "published",
    views: 180,
    postStatus: "rejected",
    email: "khaled@example.com",
    reviewedBy: "admin@example.com",
    reviewNote: "Needs clearer examples and comparison charts",
  },
  {
    id: "post-8",
    title: "Mindfulness Practices",
    excerpt: "How to stay present in a busy world...",
    category: "Lifestyle",
    featuredImage: "/assets/blogs/mindfulness.jpg",
    author: "Fatma Saad",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Fatma",
    date: "2025-12-23",
    content: "Mindfulness helps reduce stress and increase focus...",
    tags: ["Mindfulness", "Wellness", "Lifestyle"],
    expertInsight: "Practice mindfulness daily, even for 5 minutes.",
    readTime: "3 min read",
    slug: "mindfulness-practices",
    metaTitle: "Mindfulness Practices",
    status: "draft",
    views: 60,
    postStatus: "pending",
    email: "fatma@example.com",
  },
  {
    id: "post-9",
    title: "Startup Funding",
    excerpt: "Ways to fund your startup effectively...",
    category: "Business",
    featuredImage: "/assets/blogs/startup.jpg",
    author: "Ahmed Tarek",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ahmed",
    date: "2025-12-22",
    content: "Startups can secure funding through angel investors...",
    tags: ["Startup", "Funding", "Business"],
    expertInsight: "Focus on a clear business plan and scalable idea.",
    readTime: "7 min read",
    slug: "startup-funding",
    metaTitle: "Startup Funding",
    status: "published",
    views: 150,
    postStatus: "approved",
    email: "ahmed@example.com",
    reviewedBy: "reviewer2@example.com",
  },
  {
    id: "post-10",
    title: "JavaScript ES2025 Features",
    excerpt: "What's new in modern JavaScript...",
    category: "Tech",
    featuredImage: "/assets/blogs/javascript.jpg",
    author: "Mona Farouk",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Mona",
    date: "2025-12-21",
    content: "ES2025 introduces new syntax, built-in methods...",
    tags: ["JavaScript", "WebDev", "ES2025"],
    expertInsight: "Stay updated with new ECMAScript features.",
    readTime: "4 min read",
    slug: "javascript-es2025-features",
    metaTitle: "JavaScript ES2025 Features",
    status: "draft",
    views: 110,
    postStatus: "rejected",
    email: "mona@example.com",
    reviewedBy: "admin@example.com",
    reviewNote: "Add examples of new syntax usage",
  },
  {
    id: "post-11",
    title: "Cybersecurity Basics",
    excerpt: "Protect your digital life...",
    category: "Tech",
    featuredImage: "/assets/blogs/cybersecurity.jpg",
    author: "Yara Samir",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Yara",
    date: "2025-12-20",
    content: "Cybersecurity is crucial in today's digital age...",
    tags: ["Cybersecurity", "Tech", "Safety"],
    expertInsight: "Always update software and educate users.",
    readTime: "6 min read",
    slug: "cybersecurity-basics",
    metaTitle: "Cybersecurity Basics",
    status: "published",
    views: 95,
    postStatus: "approved",
    email: "yara@example.com",
    reviewedBy: "reviewer3@example.com",
  },
  {
    id: "post-12",
    title: "Yoga for Beginners",
    excerpt: "Start your yoga journey...",
    category: "Lifestyle",
    featuredImage: "/assets/blogs/yoga.jpg",
    author: "Dina Mahmoud",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Dina",
    date: "2025-12-19",
    content: "Yoga improves flexibility, strength, and mental clarity...",
    tags: ["Yoga", "Health", "Lifestyle"],
    expertInsight: "Consistency and proper posture are essential.",
    readTime: "5 min read",
    slug: "yoga-for-beginners",
    metaTitle: "Yoga for Beginners",
    status: "draft",
    views: 65,
    postStatus: "pending",
    email: "dina@example.com",
  },
  {
    id: "post-13",
    title: "Data Science Trends",
    excerpt: "What's trending in data science...",
    category: "Tech",
    featuredImage: "/assets/blogs/data-science.jpg",
    author: "Ramy Adel",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ramy",
    date: "2025-12-18",
    content: "Data science is evolving rapidly with AI integration...",
    tags: ["Data Science", "AI", "Analytics"],
    expertInsight: "Learn Python, R, and cloud platforms.",
    readTime: "8 min read",
    slug: "data-science-trends",
    metaTitle: "Data Science Trends",
    status: "published",
    views: 175,
    postStatus: "approved",
    email: "ramy@example.com",
    reviewedBy: "admin@example.com",
  },
  {
    id: "post-14",
    title: "Personal Finance Tips",
    excerpt: "Manage your money wisely...",
    category: "Lifestyle",
    featuredImage: "/assets/blogs/finance.jpg",
    author: "Mariam Fathy",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Mariam",
    date: "2025-12-17",
    content: "Budgeting, saving, and investing are key...",
    tags: ["Finance", "Budget", "Lifestyle"],
    expertInsight: "Track expenses and plan investments.",
    readTime: "6 min read",
    slug: "personal-finance-tips",
    metaTitle: "Personal Finance Tips",
    status: "draft",
    views: 50,
    postStatus: "rejected",
    email: "mariam@example.com",
    reviewedBy: "reviewer1@example.com",
    reviewNote: "Needs examples of budgeting tools",
  },
  {
    id: "post-15",
    title: "Photography Basics",
    excerpt: "Capture stunning photos...",
    category: "Lifestyle",
    featuredImage: "/assets/blogs/photography.jpg",
    author: "Ali Nabil",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ali",
    date: "2025-12-16",
    content: "Photography involves understanding lighting and composition...",
    tags: ["Photography", "Art", "Lifestyle"],
    expertInsight: "Practice regularly and analyze your shots.",
    readTime: "7 min read",
    slug: "photography-basics",
    metaTitle: "Photography Basics",
    status: "published",
    views: 130,
    postStatus: "approved",
    email: "ali@example.com",
    reviewedBy: "reviewer2@example.com",
  },
  {
    id: "post-16",
    title: "React State Management",
    excerpt: "Handle state efficiently in React...",
    category: "Tech",
    featuredImage: "/assets/blogs/react-state.jpg",
    author: "Nada Samy",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Nada",
    date: "2025-12-15",
    content: "State management is essential in React apps...",
    tags: ["React", "State", "WebDev"],
    expertInsight: "Start simple and scale state management.",
    readTime: "6 min read",
    slug: "react-state-management",
    metaTitle: "React State Management",
    status: "draft",
    views: 90,
    postStatus: "pending",
    email: "nada@example.com",
  },
  {
    id: "post-17",
    title: "Meditation Techniques",
    excerpt: "Find inner peace and focus...",
    category: "Lifestyle",
    featuredImage: "/assets/blogs/meditation.jpg",
    author: "Salma Nassar",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Salma",
    date: "2025-12-14",
    content: "Meditation reduces stress and improves focus...",
    tags: ["Meditation", "Wellness", "Lifestyle"],
    expertInsight: "Consistency is more important than duration.",
    readTime: "4 min read",
    slug: "meditation-techniques",
    metaTitle: "Meditation Techniques",
    status: "published",
    views: 115,
    postStatus: "approved",
    email: "salma@example.com",
    reviewedBy: "admin@example.com",
  },
  {
    id: "post-18",
    title: "Cloud Computing Essentials",
    excerpt: "Understanding cloud technology...",
    category: "Tech",
    featuredImage: "/assets/blogs/cloud.jpg",
    author: "Omar Fathi",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=OmarF",
    date: "2025-12-13",
    content: "Cloud computing allows scalable and flexible IT resources...",
    tags: ["Cloud", "Tech", "WebDev"],
    expertInsight: "Focus on security and cost optimization.",
    readTime: "9 min read",
    slug: "cloud-computing-essentials",
    metaTitle: "Cloud Computing Essentials",
    status: "draft",
    views: 100,
    postStatus: "rejected",
    email: "omarf@example.com",
    reviewedBy: "reviewer3@example.com",
    reviewNote: "Add diagrams explaining cloud models",
  },
  {
    id: "post-19",
    title: "SEO Best Practices",
    excerpt: "Improve your website ranking...",
    category: "Business",
    featuredImage: "/assets/blogs/seo.jpg",
    author: "Nada Fadel",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=NadaF",
    date: "2025-12-12",
    content: "Search Engine Optimization (SEO) boosts organic traffic...",
    tags: ["SEO", "Marketing", "WebDev"],
    expertInsight: "Analyze analytics and update strategies.",
    readTime: "5 min read",
    slug: "seo-best-practices",
    metaTitle: "SEO Best Practices",
    status: "published",
    views: 160,
    postStatus: "approved",
    email: "nadaf@example.com",
    reviewedBy: "admin@example.com",
  },
  {
    id: "post-20",
    title: "Blockchain Basics",
    excerpt: "Understand blockchain technology...",
    category: "Tech",
    featuredImage: "/assets/blogs/blockchain.jpg",
    author: "Hany Khaled",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Hany",
    date: "2025-12-11",
    content: "Blockchain is a distributed ledger technology...",
    tags: ["Blockchain", "Crypto", "Tech"],
    expertInsight: "Focus on security and smart contracts.",
    readTime: "7 min read",
    slug: "blockchain-basics",
    metaTitle: "Blockchain Basics",
    status: "draft",
    views: 80,
    postStatus: "pending",
    email: "hany@example.com",
  },
  {
    id: "post-21",
    title: "Digital Art Trends",
    excerpt: "Explore the latest in digital art...",
    category: "Lifestyle",
    featuredImage: "/assets/blogs/digital-art.jpg",
    author: "Salma Adel",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=SalmaA",
    date: "2025-12-10",
    content: "Digital art is growing with tools like Procreate...",
    tags: ["Art", "Digital", "Creativity"],
    expertInsight: "Experiment with different mediums and software.",
    readTime: "6 min read",
    slug: "digital-art-trends",
    metaTitle: "Digital Art Trends",
    status: "published",
    views: 140,
    postStatus: "approved",
    email: "salmaa@example.com",
    reviewedBy: "reviewer1@example.com",
  },
  {
    id: "post-22",
    title: "Time Management Tips",
    excerpt: "Maximize productivity daily...",
    category: "Lifestyle",
    featuredImage: "/assets/blogs/time-management.jpg",
    author: "Tamer Saad",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Tamer",
    date: "2025-12-09",
    content: "Effective time management helps achieve goals...",
    tags: ["Productivity", "Time", "Lifestyle"],
    expertInsight: "Set clear goals and use tools like calendars.",
    readTime: "5 min read",
    slug: "time-management-tips",
    metaTitle: "Time Management Tips",
    status: "draft",
    views: 105,
    postStatus: "rejected",
    email: "tamer@example.com",
    reviewedBy: "admin@example.com",
    reviewNote: "Add examples of task prioritization",
  },
];


export const categories = [
  {
    id: "1",
    title: "Technology",
    slug: "tech",
    description: "Latest tech news and innovations",
    postCount: 234,
    color: "bg-blue-500",
    createdAt: "2024-01-01",
    icon: "💻",
  },
  {
    id: "2",
    title: "Design",
    slug: "design",
    description: "UI/UX and graphic design trends",
    postCount: 189,
    color: "bg-purple-500",
    createdAt: "2024-01-02",
    icon: "🎨",
  },
  {
    id: "3",
    title: "Business",
    slug: "business",
    description: "Business strategies and entrepreneurship",
    postCount: 145,
    color: "bg-green-500",
    createdAt: "2024-01-03",
    icon: "📊",
  },

  {
    id: "4",
    title: "Writing",
    slug: "Writing",
    description: "Digital writing and SEO tips",
    postCount: 98,
    color: "bg-orange-500",
    createdAt: "2024-01-04",
    icon: "✍️",
  },
  {
    id: "5",
    title: "Lifestyle",
    slug: "lifestyle",
    description: "Life, health, and wellness",
    postCount: 76,
    color: "bg-pink-500",
    createdAt: "2024-01-05",
    icon: "🌿",
  },
];
